### ISSUE TITLE
Features for v0.2.0

### ISSUE THREAD

**Issue by wlis** [facebook/fixed-data-table#105]
We plan to implement following improvements for v0.2.0 (the next release).

- [x] Don't absorb the wheel event if scroll is at the end of range #33 #84
- [ ] Only render visible columns #49 
- [x] Investigate weird errors with React 0.13 #104 #83
- [x] Fix vertical positioning errors and pixels bleeding through 1px gaps
- [x] Improve Firefox perf #5
- [x] Use Babel for transform (remove the need for global polyfills, `Object.assign`) #102 
- [x] Add UMD support to dist build #103 
- [ ] Implement groupHeaderRenderer #41 
- [x] Make footer stay on the bottom when using Height prop #97 
- [ ] Create new API for rendering cells using react components instead of cellRenderers
- [x] Unify footer data API with header/groupHeader data API

**Comment by TomClarkson** [comment]
Can you add fixing #41 to this too :)

**Comment by pieterv** [comment]
@TomClarkson Sure that should be doable

**Comment by RaviKiran-IO** [comment]
Hi is possible to query ?  through the table ?

**Comment by cosminnicula** [comment]
@raaka1 check out this issue #67: you'll find a filtering example there (http://jsbin.com/temufa/14/edit)

**Comment by pieterv** [comment]
This release is out! https://github.com/facebook/fixed-data-table/releases/tag/v0.2.0

**Comment by cosminnicula** [comment]
Wonderful work. Thanks!
